default_install_hook_types:
  - pre-commit
  - commit-msg
  - post-commit
  - pre-push

repos:
  - repo: .
    rev: v0.2.2
    hooks:
      - id: troi_lab_base_hooks
      - id: check-commit-msg
      - id: recreate-changelog
      - id: bump-version
      - id: bump-version-tag-pusher
