name: Bump patch on PR on renovate-update
on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - src/commit_hooks/templates/configs/pre-commit-cfg_base.yaml
      - src/commit_hooks/templates/configs/pre-commit-cfg_python.yaml
      - pyproject.toml

jobs:
 bump-version:
    # if: ${{ startsWith(github.event.head_commit.message, 'chore(deps):') }}
    #if: ${{ github.actor == 'renovate[bot]' }}
    if: ${{ github.event.pull_request.merged }}
    name: "bump-version"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: true
      - uses: qoomon/actions--setup-git@v1
        with:
          user: committer
      - name: Install uv
        uses: astral-sh/setup-uv@v8.1.0
        with:
          enable-cache: true
      - name: Install dependencies
        run: |
          uv sync --all-extras
      - name: Bump version
        run: uv run bump_version
        env:
          BUMP: patch
      - name: Git push
        run: |
          git status
          git push
      - name: Tag-pusher
        run: uv run bump_version_tagpusher
