name: Bump version
on:
  push:
    branches:
      - main

jobs:
 pre-commit:
    if: ${{ startsWith(github.event.head_commit.message, 'chore(deps):') }}
    name: "pre-commit checks"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true
      - name: Set up Python 3.12
        run: uv python install 3.12
      - name: Install dependencies
        run: uv pip install bump-my-version
      - name: Bump-my-version
        run: uv run bump-my-version bump patch --config-file src/commit_hooks/templates/configs/cfg_version_bump.toml --tag --commit
