name: Bump version
on:
  push:
    branches:
      - main

jobs:
 bump:
    if: ${{ startsWith(github.event.head_commit.message, 'chore(deps):') }}
    runs-on: ubuntu-latest
    steps:
      - name: Bump version and tag it 
        run: |
          pip install uv
          uv pip install --system -e .  
          BUMP="patch" bump_version
