name: Releases

on:
  push:
    tags:
    - '*'
  workflow_run:
    workflows: [Bump patch on PR on renovate-update]
    types:
      - completed

jobs:

  create_release:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Create Release

    steps:
      - uses: actions/checkout@v6
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
