name: Releases

on:
  workflow_dispatch:
  push:
    tags:
    - '*'

jobs:

  create_release:
    if: ${{ github.ref != 'refs/heads/v1' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    name: Create Release

    steps:
      - uses: actions/checkout@v6
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
